<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.automationstudio</groupId>
    <artifactId>automation-studio-reactor</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>engines/engine-plugin-sdk</module>
        <module>engines/engine-plugin-conformance</module>
        <module>engines/sample-engine-plugin</module>
        <module>engines/rest-assured-engine-plugin</module>
        <module>engines/karate-worker-runtime</module>
        <module>engines/karate-gateway-runtime</module>
        <module>engines/karate-engine-plugin</module>
        <module>engines/selenium-engine-plugin</module>
        <module>backend/studio-api</module>
    </modules>
</project>
