-- AS-007: Core execution schema for Automation Studio.
-- UUID values will be generated by the application layer.

CREATE TABLE project (
    id UUID PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_project_name UNIQUE (name),
    CONSTRAINT chk_project_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED'))
);


CREATE TABLE environment (
    id UUID PRIMARY KEY,
    project_id UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    base_url VARCHAR(500) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_environment_project
        FOREIGN KEY (project_id)
        REFERENCES project (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_environment_project_name
        UNIQUE (project_id, name),

    CONSTRAINT chk_environment_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


CREATE TABLE test_suite (
    id UUID PRIMARY KEY,
    project_id UUID NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    engine_type VARCHAR(50) NOT NULL,
    suite_reference VARCHAR(300) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_test_suite_project
        FOREIGN KEY (project_id)
        REFERENCES project (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_test_suite_project_name
        UNIQUE (project_id, name),

    CONSTRAINT chk_test_suite_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED'))
);


CREATE TABLE execution (
    id UUID PRIMARY KEY,
    project_id UUID NOT NULL,
    environment_id UUID NOT NULL,
    test_suite_id UUID NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    requested_by VARCHAR(150) NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,

    total_tests INTEGER,
    passed_tests INTEGER,
    failed_tests INTEGER,

    error_message TEXT,
    version BIGINT NOT NULL DEFAULT 0,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_execution_project
        FOREIGN KEY (project_id)
        REFERENCES project (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_execution_environment
        FOREIGN KEY (environment_id)
        REFERENCES environment (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_execution_test_suite
        FOREIGN KEY (test_suite_id)
        REFERENCES test_suite (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_execution_status
        CHECK (
            status IN (
                'PENDING',
                'CLAIMED',
                'RUNNING',
                'PASSED',
                'FAILED',
                'CANCELLED',
                'ERROR'
            )
        ),

    CONSTRAINT chk_execution_total_tests
        CHECK (total_tests IS NULL OR total_tests >= 0),

    CONSTRAINT chk_execution_passed_tests
        CHECK (passed_tests IS NULL OR passed_tests >= 0),

    CONSTRAINT chk_execution_failed_tests
        CHECK (failed_tests IS NULL OR failed_tests >= 0),

    CONSTRAINT chk_execution_test_counts
        CHECK (
            total_tests IS NULL
            OR (
                COALESCE(passed_tests, 0)
                + COALESCE(failed_tests, 0)
                <= total_tests
            )
        ),

    CONSTRAINT chk_execution_time_order
        CHECK (
            finished_at IS NULL
            OR started_at IS NULL
            OR finished_at >= started_at
        )
);


CREATE TABLE execution_artifact (
    id UUID PRIMARY KEY,
    execution_id UUID NOT NULL,
    artifact_type VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    storage_location TEXT NOT NULL,
    content_type VARCHAR(150),
    size_bytes BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_execution_artifact_execution
        FOREIGN KEY (execution_id)
        REFERENCES execution (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_execution_artifact_size
        CHECK (size_bytes IS NULL OR size_bytes >= 0)
);


CREATE INDEX idx_environment_project_id
    ON environment (project_id);

CREATE INDEX idx_test_suite_project_id
    ON test_suite (project_id);

CREATE INDEX idx_execution_project_id
    ON execution (project_id);

CREATE INDEX idx_execution_environment_id
    ON execution (environment_id);

CREATE INDEX idx_execution_test_suite_id
    ON execution (test_suite_id);

CREATE INDEX idx_execution_status_requested_at
    ON execution (status, requested_at);

CREATE INDEX idx_execution_artifact_execution_id
    ON execution_artifact (execution_id);