package com.automationstudio.engine.karate.gateway;
import static org.junit.jupiter.api.Assertions.*;import java.net.*;import org.junit.jupiter.api.Test;
class GatewayTargetPolicyTest{
 @Test void bindsAuthorizationToValidatedAnswers()throws Exception{InetAddress first=InetAddress.getByName("93.184.216.34"),second=InetAddress.getByName("93.184.216.35");var target=new GatewayTargetPolicy("https://example.com",GatewayTargetPolicy.AddressPolicy.GLOBAL_ONLY,h->new InetAddress[]{first,second}).authorize("https://example.com/api?q=x");assertEquals("example.com",target.host());assertEquals(java.util.List.of(first,second),target.addresses());}
 @Test void productionDeniesOriginTricksAndIpv4Ipv6Loopback()throws Exception{var v4=new GatewayTargetPolicy("https://example.com",GatewayTargetPolicy.AddressPolicy.GLOBAL_ONLY,h->new InetAddress[]{InetAddress.getByName("127.0.0.1")});assertCode("GATEWAY_TARGET_DENIED",()->v4.authorize("https://other.example/api"));assertCode("GATEWAY_TARGET_INVALID",()->v4.authorize("https://user@example.com/api"));assertCode("GATEWAY_TARGET_INVALID",()->v4.authorize("https://example.com/api#fragment"));assertThrows(RuntimeException.class,()->new GatewayTargetPolicy("http://0177.0.0.1",GatewayTargetPolicy.AddressPolicy.GLOBAL_ONLY));assertCode("GATEWAY_ADDRESS_DENIED",()->v4.authorize("https://example.com/api"));var v6=new GatewayTargetPolicy("http://localhost",GatewayTargetPolicy.AddressPolicy.GLOBAL_ONLY,h->new InetAddress[]{InetAddress.getByName("::1")});assertCode("GATEWAY_ADDRESS_DENIED",()->v6.authorize("http://localhost/"));}
 @Test void testPolicyAdmitsOnlyIpv4AndIpv6Loopback()throws Exception{for(String address:java.util.List.of("127.0.0.1","::1")){var policy=new GatewayTargetPolicy("http://localhost:8080",GatewayTargetPolicy.AddressPolicy.LOOPBACK_ONLY_TEST,h->new InetAddress[]{InetAddress.getByName(address)});assertDoesNotThrow(()->policy.authorize("http://localhost:8080/fixture"));}}
 @Test void testPolicyRejectsPrivateSiteLocalLinkLocalAndGlobal()throws Exception{for(String address:java.util.List.of("10.0.0.1","172.16.0.1","192.168.0.1","169.254.1.1","fe80::1","93.184.216.34")){var policy=new GatewayTargetPolicy("http://fixture:8080",GatewayTargetPolicy.AddressPolicy.LOOPBACK_ONLY_TEST,h->new InetAddress[]{InetAddress.getByName(address)});assertCode("GATEWAY_ADDRESS_DENIED",()->policy.authorize("http://fixture:8080/"));}}
 private static void assertCode(String code,Runnable action){var error=assertThrows(GatewayTargetPolicy.GatewayFailure.class,action::run);assertEquals(code,error.code());}
}
