package com.automationstudio.engine.karate.gateway;
import static org.junit.jupiter.api.Assertions.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import org.junit.jupiter.api.Test;
class GatewayAuthenticationTest{
 private final GatewayTargetPolicy.Authorized target=new GatewayTargetPolicy.Authorized(URI.create("https://example.com/api?x=1"),"example.com",List.of(InetAddress.getLoopbackAddress()));
 @Test void injectsBearerAndRejectsWorkerOverrideBeforeBrokerRequest()throws Exception{var output=new ByteArrayOutputStream();try(var authorized=GatewayAuthentication.materialize(response("token"),new DataOutputStream(output),"BEARER","",target,request(Map.of()))){assertEquals("Bearer token",authorized.request().headers().get("Authorization").getFirst());}assertEquals(1,new DataInputStream(new ByteArrayInputStream(output.toByteArray())).readInt());var deniedOutput=new ByteArrayOutputStream();var conflict=assertThrows(GatewayTargetPolicy.GatewayFailure.class,()->GatewayAuthentication.materialize(response("token"),new DataOutputStream(deniedOutput),"BEARER","",target,request(Map.of("authorization",List.of("worker")))));assertEquals("AUTH_CONFIGURATION_CONFLICT",conflict.code());assertEquals(0,deniedOutput.size());}
 @Test void rejectsWorkerAuthorizationForEveryAuthenticationModeBeforeBrokerRequest()throws Exception{var modes=List.of(new String[]{"NONE",""},new String[]{"BEARER",""},new String[]{"BASIC",""},new String[]{"API_KEY_HEADER","X-Api-Key"},new String[]{"API_KEY_QUERY","api_key"});for(int i=0;i<modes.size();i++){String[] mode=modes.get(i);var brokerRequest=new ByteArrayOutputStream();String header=i%2==0?"Authorization":"aUtHoRiZaTiOn";var conflict=assertThrows(GatewayTargetPolicy.GatewayFailure.class,()->GatewayAuthentication.materialize(response("secret-canary"),new DataOutputStream(brokerRequest),mode[0],mode[1],target,request(Map.of(header,List.of("worker-canary")))));assertEquals("AUTH_CONFIGURATION_CONFLICT",conflict.code());assertFalse(conflict.getMessage().contains("worker-canary"));assertFalse(conflict.getMessage().contains("secret-canary"));assertEquals(0,brokerRequest.size());}}
 @Test void rejectsCaseVariantDuplicateAuthorizationBeforeBrokerRequest()throws Exception{Map<String,List<String>> headers=new LinkedHashMap<>();headers.put("Authorization",List.of("first-canary"));headers.put("authorization",List.of("second-canary"));var brokerRequest=new ByteArrayOutputStream();var conflict=assertThrows(GatewayTargetPolicy.GatewayFailure.class,()->GatewayAuthentication.materialize(response("secret-canary"),new DataOutputStream(brokerRequest),"NONE","",target,request(headers)));assertEquals("AUTH_CONFIGURATION_CONFLICT",conflict.code());assertEquals(0,brokerRequest.size());}
 @Test void constructsBasicAndApiKeyPlacementsAndRejectsCollisions()throws Exception{try(var basic=GatewayAuthentication.materialize(response("user","pass"),new DataOutputStream(OutputStream.nullOutputStream()),"BASIC","",target,request(Map.of()))){assertTrue(basic.request().headers().get("Authorization").getFirst().startsWith("Basic "));}try(var header=GatewayAuthentication.materialize(response("key"),new DataOutputStream(OutputStream.nullOutputStream()),"API_KEY_HEADER","X-Api-Key",target,request(Map.of()))){assertEquals("key",header.request().headers().get("X-Api-Key").getFirst());}try(var query=GatewayAuthentication.materialize(response("key"),new DataOutputStream(OutputStream.nullOutputStream()),"API_KEY_QUERY","api_key",target,request(Map.of()))){assertTrue(query.target().uri().getRawQuery().contains("api_key=key"));}assertEquals("AUTH_CONFIGURATION_CONFLICT",assertThrows(GatewayTargetPolicy.GatewayFailure.class,()->GatewayAuthentication.materialize(response("secret-canary"),new DataOutputStream(OutputStream.nullOutputStream()),"API_KEY_QUERY","x",target,request(Map.of()))).code());}
 private GatewayTransport.Request request(Map<String,List<String>> headers){return new GatewayTransport.Request("GET",target.uri().toString(),headers,new byte[0]);}
 private DataInputStream response(String... values)throws IOException{var bytes=new ByteArrayOutputStream();var out=new DataOutputStream(bytes);out.writeInt(0);out.writeInt(values.length);for(String value:values)text(out,value);return new DataInputStream(new ByteArrayInputStream(bytes.toByteArray()));}
 private void text(DataOutputStream out,String value)throws IOException{byte[] bytes=value.getBytes(StandardCharsets.UTF_8);out.writeInt(bytes.length);out.write(bytes);}
}
