#define _GNU_SOURCE
#include <arpa/inet.h>
#include <fcntl.h>
#include <linux/capability.h>
#include <linux/fib_rules.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <net/if.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <unistd.h>

static int addattr(struct nlmsghdr*n,size_t max,int type,const void*data,size_t len){size_t total=RTA_LENGTH(len),next=NLMSG_ALIGN(n->nlmsg_len)+RTA_ALIGN(total);if(next>max)return-1;struct rtattr*r=(struct rtattr*)((char*)n+NLMSG_ALIGN(n->nlmsg_len));r->rta_type=type;r->rta_len=(unsigned short)total;memcpy(RTA_DATA(r),data,len);n->nlmsg_len=(unsigned)next;return 0;}
static int hex64(const char*s){if(!s||strlen(s)!=64)return 0;for(int i=0;i<64;i++)if(!((s[i]>='0'&&s[i]<='9')||(s[i]>='a'&&s[i]<='f')))return 0;return 1;}
static int capabilities(void){struct __user_cap_header_struct h={_LINUX_CAPABILITY_VERSION_3,0};struct __user_cap_data_struct d[2]={{0}};if(getuid()==0||syscall(SYS_capget,&h,d))return 0;uint64_t e=(uint64_t)d[0].effective|((uint64_t)d[1].effective<<32),p=(uint64_t)d[0].permitted|((uint64_t)d[1].permitted<<32),allowed=(1ULL<<CAP_NET_ADMIN)|(1ULL<<CAP_SYS_ADMIN);return e==allowed&&p==allowed&&!d[0].inheritable&&!d[1].inheritable;}
static int sealed_process(long pid,unsigned long long expected_start,const char*worker){char path[64],buffer[8192];snprintf(path,sizeof(path),"/proc/%ld/stat",pid);int fd=open(path,O_RDONLY|O_CLOEXEC);if(fd<0)return 0;ssize_t size=read(fd,buffer,sizeof(buffer)-1);close(fd);if(size<=0)return 0;buffer[size]='\0';char*cursor=strrchr(buffer,')');if(!cursor)return 0;cursor+=2;char*save=NULL,*token=strtok_r(cursor," ",&save);int field=3;unsigned long long start=0;while(token){if(field++==22){start=strtoull(token,NULL,10);break;}token=strtok_r(NULL," ",&save);}if(start!=expected_start)return 0;snprintf(path,sizeof(path),"/proc/%ld/cgroup",pid);fd=open(path,O_RDONLY|O_CLOEXEC);if(fd<0)return 0;size=read(fd,buffer,sizeof(buffer)-1);close(fd);if(size<=0)return 0;buffer[size]='\0';return strstr(buffer,worker)!=NULL;}
static int dump(int type,int family,unsigned seq,char*b,size_t cap,ssize_t*size){int fd=socket(AF_NETLINK,SOCK_RAW|SOCK_CLOEXEC,NETLINK_ROUTE);if(fd<0)return-1;struct{struct nlmsghdr n;struct rtgenmsg g;}q={{NLMSG_LENGTH(sizeof(struct rtgenmsg)),type,NLM_F_REQUEST|NLM_F_DUMP,seq,0},{(unsigned char)family}};struct sockaddr_nl nl={.nl_family=AF_NETLINK};if(sendto(fd,&q,q.n.nlmsg_len,0,(struct sockaddr*)&nl,sizeof(nl))<0){close(fd);return-1;}*size=0;int done=0;while(!done){if((size_t)*size==cap){close(fd);return-1;}struct sockaddr_nl from={0};struct iovec iov={b+*size,cap-(size_t)*size};struct msghdr msg={.msg_name=&from,.msg_namelen=sizeof(from),.msg_iov=&iov,.msg_iovlen=1};ssize_t got=recvmsg(fd,&msg,0);if(got<=0||(msg.msg_flags&MSG_TRUNC)||from.nl_pid!=0){close(fd);return-1;}ssize_t remaining=got;for(struct nlmsghdr*n=(void*)(b+*size);NLMSG_OK(n,(unsigned)remaining);n=NLMSG_NEXT(n,remaining)){if(n->nlmsg_seq!=seq||n->nlmsg_pid!=0){close(fd);return-1;}if(n->nlmsg_type==NLMSG_ERROR){struct nlmsgerr*e=NLMSG_DATA(n);if(n->nlmsg_len<NLMSG_LENGTH(sizeof(*e))||e->error){close(fd);return-1;}}if(n->nlmsg_type==NLMSG_DONE)done=1;}if(remaining!=0){close(fd);return-1;}*size+=got;}close(fd);return done?0:-1;}
static int rules_ok(void){char b[16384];ssize_t size;if(dump(RTM_GETRULE,AF_UNSPEC,21,b,sizeof(b),&size))return 0;int standard=0;for(struct nlmsghdr*n=(void*)b;NLMSG_OK(n,(unsigned)size);n=NLMSG_NEXT(n,size)){if(n->nlmsg_type==NLMSG_DONE)break;if(n->nlmsg_type!=RTM_NEWRULE)return 0;struct fib_rule_hdr*r=NLMSG_DATA(n);if(r->family!=AF_INET&&r->family!=AF_INET6)continue;if(r->table!=RT_TABLE_LOCAL&&r->table!=RT_TABLE_MAIN&&r->table!=RT_TABLE_DEFAULT)return 0;int len=NLMSG_PAYLOAD(n,sizeof(*r));for(struct rtattr*a=(void*)((char*)r+NLMSG_ALIGN(sizeof(*r)));RTA_OK(a,len);a=RTA_NEXT(a,len))if(a->rta_type==FRA_FWMARK||a->rta_type==FRA_IIFNAME||a->rta_type==FRA_OIFNAME||a->rta_type==FRA_GOTO)return 0;standard++;}return standard>=3;}
static int addresses_ok(unsigned expected_if,struct in_addr worker){char b[65536];ssize_t size;if(dump(RTM_GETADDR,AF_UNSPEC,22,b,sizeof(b),&size))return 0;int matches=0;unsigned lo=if_nametoindex("lo");for(struct nlmsghdr*n=(void*)b;NLMSG_OK(n,(unsigned)size);n=NLMSG_NEXT(n,size)){if(n->nlmsg_type==NLMSG_DONE)break;if(n->nlmsg_type!=RTM_NEWADDR)return 0;struct ifaddrmsg*a=NLMSG_DATA(n);if(a->ifa_index!=expected_if&&a->ifa_index!=lo)return 0;if(a->ifa_family==AF_INET6&&a->ifa_index==expected_if)return 0;if(a->ifa_index!=expected_if||a->ifa_family!=AF_INET)continue;int len=IFA_PAYLOAD(n),exact=0;for(struct rtattr*r=IFA_RTA(a);RTA_OK(r,len);r=RTA_NEXT(r,len))if(r->rta_type==IFA_LOCAL||r->rta_type==IFA_ADDRESS){struct in_addr v;memcpy(&v,RTA_DATA(r),sizeof(v));if(v.s_addr!=worker.s_addr||a->ifa_prefixlen!=28)return 0;exact=1;}if(len||!exact)return 0;matches++;}return matches==1;}
static int routes_ok(unsigned expected_if,struct in_addr gateway,int canonical){char b[65536];ssize_t size;if(dump(RTM_GETROUTE,AF_INET,23,b,sizeof(b),&size))return 0;int defaults=0,match=0;unsigned lo=if_nametoindex("lo");for(struct nlmsghdr*n=(void*)b;NLMSG_OK(n,(unsigned)size);n=NLMSG_NEXT(n,size)){if(n->nlmsg_type==NLMSG_DONE)break;if(n->nlmsg_type!=RTM_NEWROUTE)return 0;struct rtmsg*r=NLMSG_DATA(n);if(r->rtm_family!=AF_INET)return 0;if(r->rtm_table!=RT_TABLE_MAIN&&r->rtm_table!=RT_TABLE_LOCAL)return 0;if(r->rtm_type!=RTN_UNICAST&&r->rtm_type!=RTN_LOCAL&&r->rtm_type!=RTN_BROADCAST)return 0;unsigned oif=0,metric=0;struct in_addr gw={0};int len=RTM_PAYLOAD(n);for(struct rtattr*a=RTM_RTA(r);RTA_OK(a,len);a=RTA_NEXT(a,len)){if(a->rta_type==RTA_MULTIPATH)return 0;if(a->rta_type==RTA_OIF)memcpy(&oif,RTA_DATA(a),sizeof(oif));else if(a->rta_type==RTA_GATEWAY)memcpy(&gw,RTA_DATA(a),sizeof(gw));else if(a->rta_type==RTA_PRIORITY)memcpy(&metric,RTA_DATA(a),sizeof(metric));}if(len||(oif&&oif!=expected_if&&oif!=lo))return 0;if(r->rtm_table==RT_TABLE_MAIN&&!r->rtm_dst_len){defaults++;if(oif==expected_if&&(!canonical||(gw.s_addr==gateway.s_addr&&metric==100)))match=1;}}return defaults==1&&match;}
static int network_ok(unsigned i,struct in_addr worker,struct in_addr gateway,int canonical){return rules_ok()&&addresses_ok(i,worker)&&routes_ok(i,gateway,canonical);}
static int replace_default(unsigned i,struct in_addr gateway){int fd=socket(AF_NETLINK,SOCK_RAW|SOCK_CLOEXEC,NETLINK_ROUTE);if(fd<0)return-1;struct{struct nlmsghdr n;struct rtmsg r;char attrs[128];}q={0};q.n.nlmsg_len=NLMSG_LENGTH(sizeof(q.r));q.n.nlmsg_type=RTM_NEWROUTE;q.n.nlmsg_seq=24;q.n.nlmsg_flags=NLM_F_REQUEST|NLM_F_ACK|NLM_F_CREATE|NLM_F_REPLACE;q.r.rtm_family=AF_INET;q.r.rtm_table=RT_TABLE_MAIN;q.r.rtm_protocol=RTPROT_STATIC;q.r.rtm_scope=RT_SCOPE_UNIVERSE;q.r.rtm_type=RTN_UNICAST;uint32_t metric=100;if(addattr(&q.n,sizeof(q),RTA_GATEWAY,&gateway,sizeof(gateway))||addattr(&q.n,sizeof(q),RTA_OIF,&i,sizeof(i))||addattr(&q.n,sizeof(q),RTA_PRIORITY,&metric,sizeof(metric))){close(fd);return-1;}struct sockaddr_nl nl={.nl_family=AF_NETLINK};if(sendto(fd,&q,q.n.nlmsg_len,0,(void*)&nl,sizeof(nl))<0){close(fd);return-1;}char reply[4096];ssize_t size=recv(fd,reply,sizeof(reply),0);struct nlmsghdr*n=(void*)reply;int ok=size>=(ssize_t)NLMSG_LENGTH(sizeof(struct nlmsgerr))&&n->nlmsg_type==NLMSG_ERROR&&n->nlmsg_seq==24&&((struct nlmsgerr*)NLMSG_DATA(n))->error==0;close(fd);return ok?0:-1;}
int main(int argc,char**argv){if(argc!=3||strcmp(argv[1],"--digest")||strlen(argv[2])!=71||strncmp(argv[2],"sha256:",7)||!capabilities())return 64;char request[4097];ssize_t count=read(0,request,sizeof(request)-1);if(count<=0||count>=4096)return 65;request[count]='\0';char*fields[14],*save=NULL,*part=strtok_r(request,";",&save);int n=0;while(part&&n<14){fields[n++]=part;part=strtok_r(NULL,";",&save);}if(n!=14||part)return 66;int mutate=!strcmp(fields[0],"REPLACE_WORKER_DEFAULT_ROUTE");if(!mutate&&strcmp(fields[0],"INSPECT_WORKER_NETWORK_STATE"))return 67;char*end=NULL;long pid=strtol(fields[2],&end,10);if(!end||*end||pid<=0)return 68;unsigned long long start=strtoull(fields[3],&end,10);if(!end||*end||!start||!hex64(fields[1])||!hex64(fields[6])||!sealed_process(pid,start,fields[1]))return 74;unsigned long long dev=strtoull(fields[4],&end,10);if(!end||*end||!dev)return 75;unsigned long long ino=strtoull(fields[5],&end,10);if(!end||*end||!ino)return 75;unsigned long generation=strtoul(fields[10],&end,10);if(!end||*end||!generation||!fields[11][0]||!fields[12][0]||!fields[13][0])return 75;char path[64];snprintf(path,sizeof(path),"/proc/%ld/ns/net",pid);int ns=open(path,O_RDONLY|O_CLOEXEC);struct stat st;if(ns<0||fstat(ns,&st)||st.st_dev!=(dev_t)dev||st.st_ino!=(ino_t)ino||setns(ns,CLONE_NEWNET)){if(ns>=0)close(ns);return 69;}close(ns);unsigned i=if_nametoindex(fields[9]);struct in_addr worker,gateway;if(!i||inet_pton(AF_INET,fields[7],&worker)!=1||inet_pton(AF_INET,fields[8],&gateway)!=1)return 70;if(mutate&&!network_ok(i,worker,gateway,0))return 76;if(mutate&&replace_default(i,gateway))return 71;if(!network_ok(i,worker,gateway,1))return 72;if(write(1,"ROUTE_CANONICAL",15)!=15)return 73;return 0;}
