package com.automationstudio.engine.karate.worker;
import static org.junit.jupiter.api.Assertions.*;import java.nio.file.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;
class KarateSequentialExecutorTest{
 @TempDir Path temp;private UUID id;private String gateway;
 @BeforeEach void setup(){id=UUID.randomUUID();gateway="http://as-karate-gateway-"+id.toString().replace("-","")+":8080/dispatch";SequentialProbe.reset();}
 @Test void executesMultipleScenariosWithEffectiveConcurrencyOne()throws Exception{Path root=root();write(root,"features/a.feature","Feature: sequential\nScenario: one\n* def Probe = Java.type('com.automationstudio.engine.karate.worker.SequentialProbe')\n* eval Probe.run()\nScenario: two\n* def Probe = Java.type('com.automationstudio.engine.karate.worker.SequentialProbe')\n* eval Probe.run()");var r=execute(root,List.of("features/a.feature"),List.of(),Map.of());assertEquals("SUCCEEDED",r.outcome());assertEquals(2,r.scenarios());assertEquals(2,r.passed());assertEquals(1,SequentialProbe.maximum());}
 @Test void appliesExactTagsAndNonSecretVariables()throws Exception{Path root=root();write(root,"features/a.feature","Feature: selection\n@run\nScenario: selected\n* match answer == '42'\n@skip\nScenario: excluded\n* match false == true");var r=execute(root,List.of("features/a.feature"),List.of("@run"),Map.of("answer","42"));assertEquals("SUCCEEDED",r.outcome());assertEquals(1,r.scenarios());}
 @Test void normalizesAssertionFailureAndMalformedRuntime()throws Exception{Path root=root();write(root,"features/fail.feature","Feature: fail\nScenario: fail\n* match 1 == 2");var failed=execute(root,List.of("features/fail.feature"),List.of(),Map.of());assertEquals("FAILED",failed.outcome());assertEquals("KARATE_ASSERTION_FAILED",failed.diagnostic());write(root,"features/bad.feature","not a feature");var bad=execute(root,List.of("features/bad.feature"),List.of(),Map.of());assertEquals("ERROR",bad.outcome());assertEquals("KARATE_RUNTIME_ERROR",bad.diagnostic());}
 private KarateSequentialExecutor.Result execute(Path root,List<String> paths,List<String> tags,Map<String,String> variables){return new KarateSequentialExecutor().execute(root,paths,tags,List.of(),variables,gateway,id);}
 private Path root()throws Exception{Path root=temp.resolve(UUID.randomUUID().toString()).resolve("source");Files.createDirectories(root);return root;}private static void write(Path root,String path,String text)throws Exception{Path file=root.resolve(path);Files.createDirectories(file.getParent());Files.writeString(file,text);}
}
