package com.automationstudio.engine.karate.worker;
import static org.junit.jupiter.api.Assertions.*;import java.nio.file.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;
class KarateSequentialExecutorTest{
 @TempDir Path temp;private UUID id;private String gateway;
 @BeforeEach void setup(){id=UUID.randomUUID();gateway="http://as-karate-gateway-"+id.toString().replace("-","")+":8080/dispatch";SequentialProbe.reset();}
 @Test void executesMultipleScenariosWithEffectiveConcurrencyOne()throws Exception{Path root=root();write(root,"features/a.feature",probeFeature(2,false));var r=execute(root,List.of("features/a.feature"),List.of(),Map.of(),1);assertEquals("SUCCEEDED",r.outcome());assertEquals(2,r.scenarios());assertEquals(2,r.passed());assertEquals(1,SequentialProbe.maximum());}
 @Test void boundsParallelScenariosAndRetainsEveryResult()throws Exception{Path root=root();write(root,"features/a.feature",probeFeature(6,false));var r=execute(root,List.of("features/a.feature"),List.of(),Map.of(),2);assertEquals("SUCCEEDED",r.outcome());assertEquals(6,r.scenarios());assertEquals(6,r.passed());assertEquals(0,r.failed());assertEquals(2,SequentialProbe.maximum());}
 @Test void aggregatesAssertionFailureAcrossParallelScenarios()throws Exception{Path root=root();write(root,"features/a.feature",probeFeature(5,true));var r=execute(root,List.of("features/a.feature"),List.of(),Map.of(),3);assertEquals("FAILED",r.outcome());assertEquals(5,r.scenarios());assertEquals(4,r.passed());assertEquals(1,r.failed());assertEquals("KARATE_ASSERTION_FAILED",r.diagnostic());assertTrue(SequentialProbe.maximum()<=3);}
 @Test void preservesIdentityAndOutcomeWhenCompletionOrderDiffersFromSourceOrder()throws Exception{Path root=root();write(root,"features/order.feature","Feature: order\nScenario: A slow pass\n* def Probe = Java.type('com.automationstudio.engine.karate.worker.SequentialProbe')\n* eval Probe.run('A', 300)\nScenario: B fast fail\n* def Probe = Java.type('com.automationstudio.engine.karate.worker.SequentialProbe')\n* eval Probe.run('B', 20)\n* match 1 == 2\nScenario: C medium pass\n* def Probe = Java.type('com.automationstudio.engine.karate.worker.SequentialProbe')\n* eval Probe.run('C', 120)");var r=execute(root,List.of("features/order.feature"),List.of(),Map.of(),3);assertEquals(List.of("B","C","A"),SequentialProbe.completed());assertEquals(3,r.scenarioResults().size());assertEquals(false,result(r,"A slow pass").failed());assertEquals(true,result(r,"B fast fail").failed());assertEquals(false,result(r,"C medium pass").failed());assertEquals("FAILED",r.outcome());assertEquals(2,r.passed());assertEquals(1,r.failed());}
 @Test void retainsDuplicateDisplayNamesAsDistinctNativeIdentities()throws Exception{Path root=root();write(root,"features/duplicates.feature","Feature: duplicates\nScenario: duplicate\n* match 1 == 1\nScenario: duplicate\n* match 2 == 2");var r=execute(root,List.of("features/duplicates.feature"),List.of(),Map.of(),2);assertEquals(2,r.scenarioResults().size());assertEquals(2,r.scenarioResults().stream().map(KarateSequentialExecutor.ScenarioExecution::identity).distinct().count());assertTrue(r.scenarioResults().stream().allMatch(s->s.name().equals("duplicate")&&!s.failed()));}
 @Test void distinguishesScenarioOutlineExampleRowsAndTheirOutcomes()throws Exception{Path root=root();write(root,"features/outline.feature","Feature: outline\nScenario Outline: row <value>\n* match <value> == <expected>\nExamples:\n| value | expected |\n| 1     | 1        |\n| 2     | 3        |");var r=execute(root,List.of("features/outline.feature"),List.of(),Map.of(),2);assertEquals(2,r.scenarioResults().size());assertEquals(Set.of(0,1),r.scenarioResults().stream().map(KarateSequentialExecutor.ScenarioExecution::exampleIndex).collect(java.util.stream.Collectors.toSet()));assertEquals(2,r.scenarioResults().stream().map(KarateSequentialExecutor.ScenarioExecution::identity).distinct().count());assertEquals(false,r.scenarioResults().stream().filter(s->s.exampleIndex()==0).findFirst().orElseThrow().failed());assertEquals(true,r.scenarioResults().stream().filter(s->s.exampleIndex()==1).findFirst().orElseThrow().failed());assertEquals("FAILED",r.outcome());}
 @Test void appliesExactTagsAndNonSecretVariables()throws Exception{Path root=root();write(root,"features/a.feature","Feature: selection\n@run\nScenario: selected\n* match answer == '42'\n@skip\nScenario: excluded\n* match false == true");var r=execute(root,List.of("features/a.feature"),List.of("@run"),Map.of("answer","42"),2);assertEquals("SUCCEEDED",r.outcome());assertEquals(1,r.scenarios());}
 @Test void normalizesMalformedRuntimeAndRejectsUnboundedParallelism()throws Exception{Path root=root();write(root,"features/bad.feature","not a feature");var bad=execute(root,List.of("features/bad.feature"),List.of(),Map.of(),1);assertEquals("ERROR",bad.outcome());assertEquals("KARATE_RUNTIME_ERROR",bad.diagnostic());assertThrows(IllegalArgumentException.class,()->execute(root,List.of("features/bad.feature"),List.of(),Map.of(),9));}
 private KarateSequentialExecutor.Result execute(Path root,List<String> paths,List<String> tags,Map<String,String> variables,int parallelism){return new KarateSequentialExecutor().execute(root,paths,tags,List.of(),variables,gateway,id,parallelism);}
 private static KarateSequentialExecutor.ScenarioExecution result(KarateSequentialExecutor.Result result,String name){return result.scenarioResults().stream().filter(s->name.equals(s.name())).findFirst().orElseThrow();}
 private static String probeFeature(int scenarios,boolean failLast){StringBuilder feature=new StringBuilder("Feature: bounded\n");for(int i=1;i<=scenarios;i++){feature.append("Scenario: scenario ").append(i).append("\n* def Probe = Java.type('com.automationstudio.engine.karate.worker.SequentialProbe')\n* eval Probe.run()\n");if(failLast&&i==scenarios)feature.append("* match 1 == 2\n");}return feature.toString();}
 private Path root()throws Exception{Path root=temp.resolve(UUID.randomUUID().toString()).resolve("source");Files.createDirectories(root);return root;}private static void write(Path root,String path,String text)throws Exception{Path file=root.resolve(path);Files.createDirectories(file.getParent());Files.writeString(file,text);}
}
