package com.automationstudio.engine.karate;

import com.automationstudio.engine.sdk.PreparedSourceAccess;
import com.automationstudio.engine.sdk.ExecutionSecretAccess;
import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;import java.util.concurrent.*;

/** Owns the execution-scoped internal network, gateway, worker, IPC, deadline, and cleanup. */
final class DockerKarateWorkerRuntime implements KarateWorkerRuntime {
    private final String workerImage,gatewayImage;private final WorkerLimits limits;private final CommandRunner commands;
    DockerKarateWorkerRuntime(){this(requiredImage("automation.karate.worker.image","WORKER_IMAGE_NOT_CONFIGURED"),requiredImage("automation.karate.gateway.image","GATEWAY_IMAGE_NOT_CONFIGURED"),WorkerLimits.defaults(),new ProcessCommandRunner());}
    DockerKarateWorkerRuntime(String workerImage,String gatewayImage,WorkerLimits limits,CommandRunner commands){this.workerImage=Objects.requireNonNull(workerImage);this.gatewayImage=Objects.requireNonNull(gatewayImage);this.limits=Objects.requireNonNull(limits);this.commands=Objects.requireNonNull(commands);}
    @Override public WorkerExecutionResult execute(UUID id,PreparedSourceAccess source,List<String> projected,List<String> features,KarateSuiteConfiguration configuration,Map<String,String> variables,String baseUrl,ExecutionSecretAccess secretAccess){
        String suffix=id.toString().replace("-","");String worker="as-karate-"+suffix,gateway="as-karate-gateway-"+suffix,network="as-karate-net-"+suffix;boolean networkCreated=false,gatewayCreated=false,workerCreated=false;Process process=null,gatewayProcess=null;long deadline=Instant.now().plus(limits.wallTime()).toEpochMilli();
        try{
            require(commands.run(DockerGatewayCommand.networkCreate(network,suffix),Duration.ofSeconds(30),limits.maxStderrBytes()),"GATEWAY_NETWORK_FAILED");networkCreated=true;
            require(commands.run(DockerGatewayCommand.create(gateway,gatewayImage,id,baseUrl,deadline,limits,false),Duration.ofSeconds(30),limits.maxStderrBytes()),"GATEWAY_START_FAILED");gatewayCreated=true;
            require(commands.run(DockerGatewayCommand.connect(network,gateway),Duration.ofSeconds(15),limits.maxStderrBytes()),"GATEWAY_NETWORK_FAILED");require(commands.run(DockerGatewayCommand.start(gateway),Duration.ofSeconds(15),limits.maxStderrBytes()),"GATEWAY_START_FAILED");
            gatewayProcess=commands.start(DockerGatewayCommand.attach(gateway));Process brokerProcess=gatewayProcess;Thread.ofVirtual().name("karate-secret-broker").start(()->{try{new GatewaySecretBroker(secretAccess,configuration).serve(brokerProcess);}catch(IOException ignored){}});
            require(commands.run(DockerWorkerCommand.create(worker,network,workerImage,limits),Duration.ofSeconds(30),limits.maxStderrBytes()),"WORKER_START_FAILED");workerCreated=true;
            process=commands.start(DockerWorkerCommand.attach(worker));Process active=process;
            try(var executor=Executors.newVirtualThreadPerTaskExecutor()){Future<WorkerExecutionResult> exchange=executor.submit(()->exchange(id,source,projected,features,configuration,variables,"http://"+gateway+":8080/dispatch",active));try{WorkerExecutionResult result=exchange.get(limits.wallTime().toMillis(),TimeUnit.MILLISECONDS);if(!process.waitFor(limits.stopGrace().toMillis(),TimeUnit.MILLISECONDS)||process.exitValue()!=0)throw failure("WORKER_EXIT_FAILED");return result;}catch(TimeoutException e){exchange.cancel(true);throw failure("EXECUTION_TIMEOUT");}catch(ExecutionException e){if(e.getCause() instanceof KarateEngineException k)throw k;throw failure("WORKER_PROTOCOL_ERROR");}}
        }catch(InterruptedException e){Thread.currentThread().interrupt();return new WorkerExecutionResult("CANCELLED",0,0,0,0,"EXECUTION_CANCELLED");}catch(IOException e){throw failure("WORKER_RUNTIME_ERROR");}
        finally{if(process!=null){try{process.getOutputStream().close();}catch(IOException ignored){}if(process.isAlive())process.destroyForcibly();}if(gatewayProcess!=null){try{gatewayProcess.getOutputStream().close();}catch(IOException ignored){}if(gatewayProcess.isAlive())gatewayProcess.destroyForcibly();}cleanupAll(worker,workerCreated,gateway,gatewayCreated,network,networkCreated);}
    }
    private WorkerExecutionResult exchange(UUID id,PreparedSourceAccess source,List<String> projected,List<String> features,KarateSuiteConfiguration configuration,Map<String,String> variables,String gateway,Process process)throws IOException{
        OutputStream out=process.getOutputStream();InputStream in=new BoundedInputStream(process.getInputStream(),limits.maxStdoutBytes());send(out,WorkerProtocol.Message.of("HELLO",id));expect(in,"READY",id);long aggregate=0;
        for(String path:projected){byte[] bytes=readBounded(source.open(path),limits.maxFrameBytes());aggregate=Math.addExact(aggregate,bytes.length);if(aggregate>32L*1024*1024)throw new IOException();String digest=HexFormat.of().formatHex(hash(bytes));send(out,new WorkerProtocol.Message("SOURCE",id,Map.of("path",path,"size",String.valueOf(bytes.length),"digest",digest,"content",Base64.getEncoder().encodeToString(bytes))));expect(in,"ACCEPTED_SOURCE",id);}
        send(out,WorkerProtocol.Message.of("COMPLETE",id));expect(in,"COMPLETED_FOUNDATION_PROOF",id);
        send(out,new WorkerProtocol.Message("EXECUTE",id,Map.of("features",encode(features),"includeTags",encode(configuration.includeTags()),"excludeTags",encode(configuration.excludeTags()),"variables",encodeMap(variables),"gateway",gateway)));
        WorkerProtocol.Message response=expect(in,"EXECUTION_RESULT",id);if(!response.fields().keySet().equals(Set.of("outcome","features","scenarios","passed","failed","diagnostic")))throw new IOException();String outcome=response.fields().get("outcome"),diagnostic=response.fields().get("diagnostic");if("ERROR".equals(outcome))throw failure(validCode(diagnostic)?diagnostic:"KARATE_RUNTIME_ERROR");WorkerExecutionResult result;try{result=new WorkerExecutionResult(outcome,Integer.parseInt(response.fields().get("features")),Integer.parseInt(response.fields().get("scenarios")),Integer.parseInt(response.fields().get("passed")),Integer.parseInt(response.fields().get("failed")),diagnostic);}catch(RuntimeException e){throw new IOException();}
        send(out,WorkerProtocol.Message.of("SHUTDOWN",id));expect(in,"BYE",id);out.close();return result;
    }
    private static boolean validCode(String code){return code!=null&&code.matches("[A-Z_]{2,40}");}
    private void cleanupContainer(String name,boolean worker){int grace=(int)Math.max(0,limits.stopGrace().toSeconds());List<String> stop=worker?DockerWorkerCommand.stop(name,grace):DockerGatewayCommand.stop(name,grace),kill=worker?DockerWorkerCommand.kill(name):DockerGatewayCommand.kill(name),remove=worker?DockerWorkerCommand.remove(name):DockerGatewayCommand.remove(name),inspect=worker?DockerWorkerCommand.inspect(name):DockerGatewayCommand.inspect(name);commands.bestEffort(stop,grace,limits.maxStderrBytes());commands.bestEffort(kill,1,limits.maxStderrBytes());commands.bestEffort(remove,5,limits.maxStderrBytes());if(commands.bestEffort(inspect,5,limits.maxStderrBytes()).exit()==0)throw failure(worker?"WORKER_CLEANUP_FAILED":"GATEWAY_CLEANUP_FAILED");}
    private void cleanupNetwork(String name){commands.bestEffort(DockerGatewayCommand.networkRemove(name),5,limits.maxStderrBytes());if(commands.bestEffort(List.of("docker","network","inspect",name),5,limits.maxStderrBytes()).exit()==0)throw failure("GATEWAY_CLEANUP_FAILED");}
    private void cleanupAll(String worker,boolean workerCreated,String gateway,boolean gatewayCreated,String network,boolean networkCreated){KarateEngineException failure=null;if(workerCreated)try{cleanupContainer(worker,true);}catch(KarateEngineException e){failure=e;}if(gatewayCreated)try{cleanupContainer(gateway,false);}catch(KarateEngineException e){if(failure==null)failure=e;else failure.addSuppressed(e);}if(networkCreated)try{cleanupNetwork(network);}catch(KarateEngineException e){if(failure==null)failure=e;else failure.addSuppressed(e);}if(failure!=null)throw failure;}
    private static void require(CommandResult r,String code){if(r.exit()!=0)throw failure(code);}
    private void send(OutputStream out,WorkerProtocol.Message m)throws IOException{WorkerProtocol.write(out,m,limits.maxFrameBytes());}
    private WorkerProtocol.Message expect(InputStream in,String type,UUID id)throws IOException{var m=WorkerProtocol.read(in,limits.maxFrameBytes());if(!m.type().equals(type)||!m.correlationId().equals(id))throw new IOException();return m;}
    private static byte[] readBounded(InputStream input,int max)throws IOException{try(input){var out=new ByteArrayOutputStream();byte[] b=new byte[8192];int total=0,n;while((n=input.read(b))>=0){total+=n;if(total>max*3/4)throw new IOException();out.write(b,0,n);}return out.toByteArray();}}
    private static byte[] hash(byte[] b){try{return MessageDigest.getInstance("SHA-256").digest(b);}catch(Exception e){throw new IllegalStateException(e);}}
    private static String encode(Collection<String> values)throws IOException{var bytes=new ByteArrayOutputStream();try(var out=new DataOutputStream(bytes)){out.writeInt(values.size());for(String value:values){byte[] b=value.getBytes(StandardCharsets.UTF_8);out.writeInt(b.length);out.write(b);}}return Base64.getEncoder().encodeToString(bytes.toByteArray());}
    private static String encodeMap(Map<String,String> values)throws IOException{List<String> pairs=new ArrayList<>();new TreeMap<>(values).forEach((k,v)->{pairs.add(k);pairs.add(v);});return encode(pairs);}
    private static KarateEngineException failure(String code){return new KarateEngineException(code,"Karate controlled execution failed");}
    interface CommandRunner{CommandResult run(List<String> c,Duration timeout,long stderr)throws IOException,InterruptedException;Process start(List<String> c)throws IOException;default CommandResult bestEffort(List<String> c,int seconds,long stderr){try{return run(c,Duration.ofSeconds(Math.max(1,seconds)),stderr);}catch(Exception e){return new CommandResult(-1,"");}}}
    record CommandResult(int exit,String output){}
    private static String requiredImage(String property,String code){String value=System.getProperty(property);if(value==null||value.isBlank())throw failure(code);return value;}
    static final class ProcessCommandRunner implements CommandRunner{public CommandResult run(List<String> c,Duration timeout,long stderr)throws IOException,InterruptedException{Process p=new ProcessBuilder(c).redirectErrorStream(true).start();ExecutorService reader=Executors.newVirtualThreadPerTaskExecutor();Future<byte[]> output=reader.submit(()->{try(var in=new BoundedInputStream(p.getInputStream(),stderr)){return in.readAllBytes();}});try{if(!p.waitFor(timeout.toMillis(),TimeUnit.MILLISECONDS)){p.destroyForcibly();p.waitFor(5,TimeUnit.SECONDS);output.cancel(true);return new CommandResult(-1,"");}try{return new CommandResult(p.exitValue(),new String(output.get(5,TimeUnit.SECONDS),StandardCharsets.UTF_8));}catch(ExecutionException e){if(e.getCause() instanceof IOException io)throw io;throw new IOException(e.getCause());}catch(TimeoutException e){p.destroyForcibly();output.cancel(true);return new CommandResult(-1,"");}}finally{reader.shutdownNow();}}public Process start(List<String> c)throws IOException{return new ProcessBuilder(c).redirectError(ProcessBuilder.Redirect.DISCARD).start();}}
}
