package com.automationstudio.engine.karate;
import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
/** Provider-side independent implementation of the versioned worker wire protocol. */
final class WorkerProtocol{
 static final int VERSION=1,DEFAULT_MAX_FRAME=1_048_576;
 record Message(String type,UUID correlationId,Map<String,String> fields){Message{if(type==null||!type.matches("[A-Z_]{2,40}")||correlationId==null)throw new IllegalArgumentException();fields=Collections.unmodifiableMap(new TreeMap<>(Objects.requireNonNull(fields)));if(fields.entrySet().stream().anyMatch(e->e.getKey()==null||!e.getKey().matches("[a-zA-Z][a-zA-Z0-9]*")||e.getValue()==null))throw new IllegalArgumentException();}static Message of(String type,UUID id){return new Message(type,id,Map.of());}}
 static void write(OutputStream output,Message m,int max)throws IOException{byte[] b=encode(m).getBytes(StandardCharsets.UTF_8);if(b.length==0||b.length>max)throw new IOException();new DataOutputStream(output).writeInt(b.length);output.write(b);output.flush();}
 static Message read(InputStream input,int max)throws IOException{DataInputStream in=new DataInputStream(input);int n=in.readInt();if(n<=0||n>max)throw new IOException();byte[] b=in.readNBytes(n);if(b.length!=n)throw new EOFException();return decode(new String(b,StandardCharsets.UTF_8));}
 private static String encode(Message m){StringBuilder b=new StringBuilder("{\"version\":1,\"type\":\"").append(escape(m.type())).append("\",\"correlationId\":\"").append(m.correlationId()).append("\",\"fields\":{");boolean first=true;for(var e:m.fields().entrySet()){if(!first)b.append(',');first=false;b.append('"').append(escape(e.getKey())).append("\":\"").append(escape(e.getValue())).append('"');}return b.append("}}").toString();}
 private static Message decode(String json)throws IOException{try{Parser p=new Parser(json);Map<String,Object> root=p.object();p.end();if(!root.keySet().equals(Set.of("version","type","correlationId","fields"))||!Integer.valueOf(VERSION).equals(root.get("version")))throw new IOException();Map<?,?> raw=(Map<?,?>)root.get("fields");Map<String,String> fields=new TreeMap<>();for(var e:raw.entrySet())fields.put((String)e.getKey(),(String)e.getValue());return new Message((String)root.get("type"),UUID.fromString((String)root.get("correlationId")),fields);}catch(IOException e){throw e;}catch(RuntimeException e){throw new IOException();}}
 private static String escape(String s){return s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r");}
 private static final class Parser{final String s;int i;Parser(String s){this.s=s;}Map<String,Object> object(){ws();expect('{');Map<String,Object> m=new LinkedHashMap<>();ws();if(take('}'))return m;do{String k=string();expect(':');Object v=value();if(m.put(k,v)!=null)throw new IllegalArgumentException();}while(take(','));expect('}');return m;}Object value(){ws();if(peek()=='"')return string();if(peek()=='{')return object();int start=i;while(i<s.length()&&Character.isDigit(s.charAt(i)))i++;if(start==i)throw new IllegalArgumentException();return Integer.valueOf(s.substring(start,i));}String string(){ws();expect('"');StringBuilder b=new StringBuilder();while(i<s.length()){char c=s.charAt(i++);if(c=='"')return b.toString();if(c=='\\'){char e=s.charAt(i++);b.append(switch(e){case '"'->'"';case '\\'->'\\';case 'n'->'\n';case 'r'->'\r';default->throw new IllegalArgumentException();});}else b.append(c);}throw new IllegalArgumentException();}void end(){ws();if(i!=s.length())throw new IllegalArgumentException();}void ws(){while(i<s.length()&&Character.isWhitespace(s.charAt(i)))i++;}char peek(){return i<s.length()?s.charAt(i):0;}boolean take(char c){ws();if(peek()==c){i++;return true;}return false;}void expect(char c){if(!take(c))throw new IllegalArgumentException();}}
 private WorkerProtocol(){}
}
