spring.application.name=studio-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/automation_studio}
spring.datasource.username=${DB_USERNAME:automation_studio}
spring.datasource.password=${DB_PASSWORD:automation_studio}

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always